//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VSMS_PRGASYS
    {
        public string COM_CODE { get; set; }
        public decimal PS_ID { get; set; }
        public decimal NO { get; set; }
        public string PRG_CODE { get; set; }
        public string SYSTEM { get; set; }
        public string MODULE { get; set; }
        public string ISSUE_BY { get; set; }
        public string CRET_BY { get; set; }
        public Nullable<System.DateTime> CRET_DATE { get; set; }
    }
}
